spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///C://Users//Nilesh//Documents//eazybank//config"
         git:
           uri: "https://github.com/NileshNSwami7/eazybank-config-microservices.git"
           default-label: main
           timeout: 5
           clone-on-start: true
           force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
    metrics:
      tags:
        application: ${spring.application.name}

encrypt:
  key: "eecf6fc4c6a1a3d64880b237e06f795c"

server:
  port: 8071




