build:
  version: "3.0.1"

cards:
  message: "Welcome to eazybank cards to related API."
  contactDetails:
    name: "Mahindra Singh"
    email: "mahindrasingh@eazybank.com"
  onCallSupport:
    - (+91) 98083 93738
    - (+91) 98083 93735